serverAddr = "你的服务器公网IP"
serverPort = 7000

auth.method = "token"
auth.token = "4788787533578"

# KidPlan 服务
[[proxies]]
name = "kidplan"
type = "http"
localIP = "127.0.0.1"
localPort = 8089
customDomains = ["kid.xyzbk.com"]
